# Generated by Django 5.0.7 on 2024-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('max_capacity', models.PositiveBigIntegerField()),
                ('department', models.CharField(max_length=20)),
                ('trainer', models.CharField(max_length=20)),
                ('pass_grade', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('assistant_trainer', models.CharField(max_length=20)),
                ('tools', models.TextField()),
            ],
        ),
    ]
