# Generated by Django 5.0.7 on 2024-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_code', models.CharField(max_length=20)),
                ('assistant_trainer_incharge', models.CharField(max_length=20)),
                ('room_number', models.SmallIntegerField()),
                ('class_rep', models.CharField(max_length=20)),
                ('number_of_tables', models.SmallIntegerField()),
                ('number_of_seats', models.SmallIntegerField()),
                ('max_number_seats', models.PositiveIntegerField()),
                ('number_of_groups', models.PositiveIntegerField()),
            ],
        ),
    ]
